### ISSUE TITLE
Not working for me on CentOS 6.5

### ISSUE THREAD

**Issue by mbn18** [sys4/pacemaker-snmp#1]
Hi,

I followed the instruction with no luck.

snmpd.conf:

```
rocommunity public 127.0.0.1
perl do '/usr/local/sbin/pcmk-subagent.pl';
```

snmp.conf:

```
mibs +PACEMAKER-MIB
mibs +SYS4-MIB
```

snmptranslate -IR -Tp sys4Pacemaker

```
+--sys4Pacemaker(4)
   +--sys4PcmkClusterConfig(1)
   +--sys4PcmkNodes(2)
   |  +-- -R-- Integer32 sys4PcmkTotalNodes(1)
   |  +-- -R-- Integer32 sys4PcmkOnlineNodes(2)
   |  |
   |  +--sys4PcmkNodeTable(3)
   |     |
   |     +--sys4PcmkNodeEntry(1)
   |        |  Index: sys4PcmkNodeIndex
   |        |
   |        +-- -R-- Integer32 sys4PcmkNodeIndex(1)
   |        +-- -R-- String    sys4PcmkNodeName(2)
   |        |        Size: 1..128
   |        +-- -R-- Integer32 sys4PcmkNodeId(3)
   |        +-- -R-- EnumVal   sys4PcmkNodeStatus(4)
   |                 Values: unknown(0), online(1), standby(2), offline(3), other(4)
   |
   +--sys4PcmkResources(3)
      +-- -R-- Integer32 sys4PcmkResourcePrimitiveNumber(1)
      +-- -R-- Integer32 sys4PcmkResourceGroupNumber(2)
      +-- -R-- Integer32 sys4PcmkResourceCloneNumber(3)
      +-- -R-- Integer32 sys4PcmkResourceMasterNumber(4)
      +-- -R-- Integer32 sys4PcmkResourceFailures(5)
      |
      +--sys4PcmkResourceTable(6)
         |
         +--sys4PcmkResourceEntry(1)
            |  Index: sys4PcmkResourceIndex
            |
            +-- -R-- Integer32 sys4PcmkResourceIndex(1)
            +-- -R-- String    sys4PcmkResourceName(2)
            +-- -R-- EnumVal   sys4PcmkResourceStatus(3)
            |        Values: Stopped(0), Started(1), Master(2), Unknown(3)
            +-- -R-- Integer32 sys4PcmkResourceFailure(4)
```
- snmpd is running as root and pacemaker is up
- snmpd ran in the foreground with no apparent error
- The following rpms are installed
  - net-snmp-5.5-49
  - net-snmp-utils
  - net-snmp-perl
  - perl-5.10.1
- I validated that all required perl module exist

Then I ran:
snmpwalk -v2c -c public localhost sys4Pacemaker

```
PACEMAKER-MIB::sys4Pacemaker = No Such Object available on this agent at this OID
```

Any idea if something is wrong or how I can track the bug (if exist).

Thanks

**Comment by misch42** [comment]
hi,

it seems it does not work on CentOS 6.5. At the moemnt I do not have the faintest idea, why it does not work. Sorry. When I find some time I will debug this in deep.

Michael.

**Comment by misch42** [comment]
Hi,

I just pushed a commit that solved the issue. I clarified two perl statements casting a "scalar" operation". Also plesae be sure to have selinux turned OFF. It prevents the snmpd from calling perl programs.

**Comment by mbn18** [comment]
Nice, I already have a solution but I will be happy to verify that this one works. Will report back.
Please assign this issue to me so I will remember to do it :)
